"""Slug generation + uniqueness on Supplier insert."""

import pytest

from app.extensions import db
from app.models.supplier import Supplier, slugify_supplier_name


class TestSlugifySupplierName:
    def test_latin_lowercase(self):
        assert slugify_supplier_name("MARESTO") == "maresto"

    def test_cyrillic_transliterated(self):
        assert slugify_supplier_name("Кодаки") == "kodaki"

    def test_ukrainian_letters(self):
        assert slugify_supplier_name("РП Україна") == "rp-ukrayina"

    def test_spaces_and_punctuation(self):
        assert slugify_supplier_name("Foo & Bar (LLC)") == "foo-bar-llc"

    def test_empty_input_default(self):
        assert slugify_supplier_name("") == "supplier"

    def test_only_punctuation_default(self):
        assert slugify_supplier_name("!!!---") == "supplier"

    def test_truncated_to_50(self):
        long_name = "a" * 80
        assert len(slugify_supplier_name(long_name)) == 50


class TestAutoSlugOnInsert:
    def test_slug_autogenerated_from_name(self, app):
        with app.app_context():
            s = Supplier(name="Merx", feed_url="http://x")
            db.session.add(s)
            db.session.commit()
            assert s.slug == "merx"

    def test_slug_collision_gets_suffix(self, app):
        with app.app_context():
            a = Supplier(name="Foo", feed_url="http://a")
            db.session.add(a)
            db.session.commit()
            b = Supplier(name="FOO", feed_url="http://b")
            db.session.add(b)
            db.session.commit()
            assert a.slug == "foo"
            assert b.slug == "foo-2"

    def test_explicit_slug_preserved(self, app):
        with app.app_context():
            s = Supplier(name="Custom", slug="my-custom", feed_url="http://x")
            db.session.add(s)
            db.session.commit()
            assert s.slug == "my-custom"
