"""One-shot read-only helper: dump remaining candidate matches with context.

Run:
    .venv/Scripts/python.exe scripts/dump_candidates.py

Outputs a markdown report grouped by supplier product so Yana can click
through them in the UI in the morning with full context on each decision.
"""

from collections import defaultdict

from app import create_app
from app.extensions import db
from app.models.catalog import PromProduct
from app.models.product_match import ProductMatch
from app.models.supplier_product import SupplierProduct
from app.services.matcher import after_brand_remainder, meaningful_tokens


def _fmt_price(cents):
    if cents is None:
        return "—"
    return f"{cents / 100:.2f}"


def main():
    app = create_app()
    with app.app_context():
        candidates = (
            db.session.query(ProductMatch)
            .filter(ProductMatch.status == "candidate")
            .order_by(ProductMatch.supplier_product_id, ProductMatch.score.desc())
            .all()
        )

        groups: dict[int, list[ProductMatch]] = defaultdict(list)
        for m in candidates:
            groups[m.supplier_product_id].append(m)

        multis = {k: v for k, v in groups.items() if len(v) > 1}
        singles = {k: v for k, v in groups.items() if len(v) == 1}

        out = []
        out.append("# Candidates to review (generated by scripts/dump_candidates.py)")
        out.append("")
        out.append(f"**Total:** {len(candidates)} candidates in {len(groups)} groups")
        out.append(f"  - Multi-candidate groups (need product knowledge): {len(multis)}")
        out.append(f"  - Single-candidate borderlines: {len(singles)}")
        out.append("")

        # Multi first — these are the hard ones
        if multis:
            out.append("## Multi-candidate groups")
            out.append("")
            for sp_id, ms in multis.items():
                sp = db.session.get(SupplierProduct, sp_id)
                if sp is None:
                    continue
                out.append(f"### Supplier: {sp.name}")
                out.append(f"- brand: {sp.brand or '—'}")
                out.append(
                    f"- supplier price: {_fmt_price(sp.price_cents)} {sp.currency or 'EUR'}"
                )
                if sp.model:
                    out.append(f"- supplier model: {sp.model}")
                out.append("")
                out.append("| match_id | score | catalog name | catalog brand | catalog price | after-brand tokens |")
                out.append("|---:|---:|---|---|---:|---|")
                for m in ms:
                    pp = db.session.get(PromProduct, m.prom_product_id)
                    if pp is None:
                        continue
                    rem = after_brand_remainder(pp.name or "", pp.brand or sp.brand)
                    toks = sorted(meaningful_tokens(rem))
                    price = _fmt_price(pp.price)
                    out.append(
                        f"| {m.id} | {m.score:.0f} | {pp.name} | {pp.brand or '—'} | {price} | `{' '.join(toks)}` |"
                    )
                out.append("")
                out.append("**Decision needed:** pick one, reject rest (or reject all if none fit).")
                out.append("")

        # Singles next — the ones that just need a yes/no click
        if singles:
            out.append("## Single-candidate borderlines")
            out.append("")
            out.append("| match_id | supplier | catalog | score | sup price | prom price | Δ% |")
            out.append("|---:|---|---|---:|---:|---:|---:|")
            for sp_id, ms in singles.items():
                m = ms[0]
                sp = db.session.get(SupplierProduct, sp_id)
                pp = db.session.get(PromProduct, m.prom_product_id)
                if sp is None or pp is None:
                    continue
                sp_price = (sp.price_cents or 0) / 100
                pp_price = (pp.price or 0) / 100
                if sp_price and pp_price:
                    delta = (pp_price - sp_price) / sp_price * 100
                    delta_str = f"{delta:+.1f}%"
                else:
                    delta_str = "—"
                out.append(
                    f"| {m.id} | {sp.name} | {pp.name} | {m.score:.0f} | "
                    f"{sp_price:.2f} | {pp_price:.2f} | {delta_str} |"
                )
            out.append("")

        output = "\n".join(out)
        dest = "instance/candidates_review.md"
        with open(dest, "w", encoding="utf-8") as f:
            f.write(output)
        print(f"Wrote {dest}")
        print(f"  {len(candidates)} candidates, {len(groups)} groups")
        print(f"  {len(multis)} multi, {len(singles)} single")


if __name__ == "__main__":
    main()
