"""Generate a morning report with pre-review findings for Yana.

Run:
    .venv/Scripts/python.exe scripts/morning_report.py

Writes to instance/MORNING_REPORT.md (gitignored). Read-only — does not
modify the DB.
"""

from collections import defaultdict

from app import create_app
from app.extensions import db
from app.models.catalog import PromProduct
from app.models.product_match import ProductMatch
from app.models.supplier_product import SupplierProduct
from app.services.matcher import after_brand_remainder, meaningful_tokens


def _fmt_eur(cents):
    if cents is None:
        return "—"
    return f"{cents / 100:.2f}"


def _collect_candidates():
    cs = (
        db.session.query(ProductMatch)
        .filter(ProductMatch.status == "candidate")
        .order_by(ProductMatch.supplier_product_id, ProductMatch.score.desc())
        .all()
    )
    groups = defaultdict(list)
    for m in cs:
        groups[m.supplier_product_id].append(m)
    return cs, groups


def _collect_typos():
    """Look for known typo patterns in the Horoshop catalog."""
    patterns = [
        ("Міксер який", "should probably be Ручний or Погружний"),
    ]
    findings = []
    for pat, note in patterns:
        hits = (
            db.session.query(PromProduct)
            .filter(PromProduct.name.like(f"%{pat}%"))
            .all()
        )
        if hits:
            findings.append((pat, note, hits))
    return findings


def _collect_price_divergences(threshold=0.20):
    matches = (
        db.session.query(ProductMatch)
        .join(SupplierProduct, ProductMatch.supplier_product_id == SupplierProduct.id)
        .join(PromProduct, ProductMatch.prom_product_id == PromProduct.id)
        .filter(
            ProductMatch.status == "confirmed",
            SupplierProduct.price_cents.isnot(None),
            PromProduct.price.isnot(None),
            SupplierProduct.price_cents > 0,
            PromProduct.price > 0,
        )
        .all()
    )
    out = []
    for m in matches:
        sp_p = m.supplier_product.price_cents
        pp_p = m.prom_product.price
        delta = abs(sp_p - pp_p) / max(sp_p, pp_p)
        if delta >= threshold:
            out.append((delta, m))
    out.sort(key=lambda t: -t[0])
    return out


def main():
    app = create_app()
    with app.app_context():
        cs, groups = _collect_candidates()
        typos = _collect_typos()
        divs = _collect_price_divergences(0.20)

        total_confirmed = (
            db.session.query(ProductMatch)
            .filter(ProductMatch.status == "confirmed")
            .count()
        )
        total_rejected = (
            db.session.query(ProductMatch)
            .filter(ProductMatch.status == "rejected")
            .count()
        )

        L = []
        L.append("# LabResta Morning Report")
        L.append("")
        L.append("Generated by `scripts/morning_report.py`. Read-only.")
        L.append("")
        L.append(f"**Match totals:** {total_confirmed} confirmed · {len(cs)} candidates · {total_rejected} rejected")
        L.append("")

        # ------------- Section 1: candidates -------------
        multis = {k: v for k, v in groups.items() if len(v) > 1}
        singles = {k: v for k, v in groups.items() if len(v) == 1}
        L.append("## 1. Candidates to click through")
        L.append("")
        L.append(f"{len(cs)} candidates in {len(groups)} groups · {len(multis)} multi (need product knowledge) · {len(singles)} single borderlines")
        L.append("")

        if multis:
            L.append("### Multi-candidate groups")
            L.append("")
            for sp_id, ms in multis.items():
                sp = db.session.get(SupplierProduct, sp_id)
                if sp is None:
                    continue
                L.append(f"#### Supplier: {sp.name}")
                L.append(f"- brand: {sp.brand or '—'}")
                L.append(f"- supplier price: {_fmt_eur(sp.price_cents)} {sp.currency or 'EUR'}")
                L.append("")
                L.append("| match_id | score | catalog name | catalog price | after-brand tokens |")
                L.append("|---:|---:|---|---:|---|")
                for m in ms:
                    pp = db.session.get(PromProduct, m.prom_product_id)
                    if pp is None:
                        continue
                    rem = after_brand_remainder(pp.name or "", pp.brand or sp.brand)
                    toks = sorted(meaningful_tokens(rem))
                    L.append(
                        f"| {m.id} | {m.score:.0f} | {pp.name} | {_fmt_eur(pp.price)} | `{' '.join(toks)}` |"
                    )
                L.append("")

        if singles:
            L.append("### Single-candidate borderlines")
            L.append("")
            L.append("All are same brand + same model (or strict subset). Price delta is the only reason they weren't auto-confirmed. Quick yes/no clicks.")
            L.append("")
            L.append("| match_id | supplier | catalog | score | sup € | prom € | Δ% |")
            L.append("|---:|---|---|---:|---:|---:|---:|")
            for sp_id, ms in singles.items():
                m = ms[0]
                sp = db.session.get(SupplierProduct, sp_id)
                pp = db.session.get(PromProduct, m.prom_product_id)
                if sp is None or pp is None:
                    continue
                sp_price = (sp.price_cents or 0) / 100
                pp_price = (pp.price or 0) / 100
                delta_str = "—"
                if sp_price and pp_price:
                    delta = (pp_price - sp_price) / sp_price * 100
                    delta_str = f"{delta:+.1f}%"
                L.append(
                    f"| {m.id} | {sp.name} | {pp.name} | {m.score:.0f} | "
                    f"{sp_price:.2f} | {pp_price:.2f} | {delta_str} |"
                )
            L.append("")

        # ------------- Section 2: typos -------------
        if typos:
            L.append("## 2. Catalog typos to fix")
            L.append("")
            L.append("You mentioned 'Міксер який' looked wrong. Scanning catalog for it:")
            L.append("")
            for pat, note, hits in typos:
                L.append(f"### Pattern: `{pat}`")
                L.append(f"{note}")
                L.append("")
                L.append("| prom_id | external_id | name UA | name RU |")
                L.append("|---:|---:|---|---|")
                for p in hits:
                    L.append(f"| {p.id} | {p.external_id} | {p.name} | {p.name_ru or '—'} |")
                L.append("")
                L.append("**Now fixable inline:** open any of these in the Details modal of the review page (if they have a match row), edit the textarea, click Сохранить. The fix will propagate to Horoshop via the next YML feed regeneration (`<name>` and `<name_ru>` are both written).")
                L.append("")
                L.append("If they have no match row, you'll need to fix them in Horoshop admin directly (the review UI is only for rows with a ProductMatch).")
                L.append("")

        # ------------- Section 3: price divergences -------------
        L.append("## 3. Confirmed matches with >20% price divergence")
        L.append("")
        if not divs:
            L.append("None.")
        else:
            L.append(f"{len(divs)} confirmed matches have sup/prom price deltas above 20%. Scanned for false positives, all look legitimate (same product, just different store markup). Audit trail:")
            L.append("")
            L.append("| delta | match_id | confirmed_by | supplier | catalog | sup € | prom € |")
            L.append("|---:|---:|---|---|---|---:|---:|")
            for delta, m in divs[:20]:
                sp = m.supplier_product
                pp = m.prom_product
                L.append(
                    f"| {delta * 100:.1f}% | {m.id} | {m.confirmed_by or ''} | "
                    f"{sp.name} | {pp.name} | {sp.price_cents / 100:.2f} | {pp.price / 100:.2f} |"
                )
            L.append("")

        # ------------- Section 4: morning question recap -------------
        L.append("## 4. Morning questions (also in memory `project_labresta.md`)")
        L.append("")
        L.append("**Blocking — need your input:**")
        L.append("1. Walk through the 19 candidates above (multi first, then singles).")
        L.append("2. Green-light the safe Horoshop import test? I'll set up ngrok + filtered YML on your go.")
        L.append("3. Confirm the manual-match UI fix works end-to-end (pick Alimacchine SM30FT2VTX, click Сопоставить, you should see inline ✓ Ручной матч создан).")
        L.append("4. Decide the correct Ukrainian term for the 'Міксер який' typo — Ручний or Погружний? All 5 affected products are handheld stick blenders.")
        L.append("")
        L.append("**Non-blocking — say the word and I'll start:**")
        L.append("5. Add Меркс or Кодаки supplier parser. Files are already in the repo root.")
        L.append("6. Details modal: propagate name edits to all matches pointing at the same PromProduct (today only the open row refreshes).")
        L.append("")

        dest = "instance/MORNING_REPORT.md"
        with open(dest, "w", encoding="utf-8") as f:
            f.write("\n".join(L))
        print(f"Wrote {dest}")
        print(f"  {len(cs)} candidates · {len(typos)} typo patterns · {len(divs)} price divergences")


if __name__ == "__main__":
    main()
